<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LDP" nsURI="http://LDP/1.0" nsPrefix="LDP">
  <eClassifiers xsi:type="ecore:EClass" name="Processus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activites" lowerBound="1"
        upperBound="-1" eType="#//Activite" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="debut" lowerBound="1" eType="#//Debut"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fin" lowerBound="1" eType="#//Fin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activiteCourante" eType="#//Activite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activite">
    <eOperations name="pasDansSuivant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="act" lowerBound="1" eType="#//Activite"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suivante" eType="#//Activite"
        eOpposite="#//Activite/precedente"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precedente" eType="#//Activite"
        eOpposite="#//Activite/suivante"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoEtat">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//Activite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Debut" eSuperTypes="#//PseudoEtat"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fin" eSuperTypes="#//PseudoEtat"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreationVar" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" lowerBound="1" eType="#//VariablePrimitif"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceObj" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objet" lowerBound="1" eType="#//Objet"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppelMethode" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultat" eType="#//VariablePrimitif"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objetAppele" lowerBound="1"
        eType="#//Objet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametre" eType="#//Parametre"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//Method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariablePrimitif" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valeur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objet" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomMethode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametre">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
</ecore:EPackage>
